### PR TITLE
Add conditional compile for init to align with ST's existing API

### PR DESCRIPTION
**Pull request by deviousasti**
Sorry to create more work for you.

This reverts the earlier PR and wraps it in a conditional compile.
Most of the commits are related to the activity/inactivity threshold, duration and interrupts which were not defined in the driver.

### CODE REVIEW

**Comment by cparata** [comment]
Hi @deviousasti ,
thanks for the PR. Regarding the activity/inactivity APIs, do you have also a sample sketch to test them with X-NUCLEO-IKS01A2? If so, could you also upload these samples in the "examples" folder? You can take inspiration from the IKS01A2 interrupt examples that I published for LSM6DSL here:
https://github.com/stm32duino/X-NUCLEO-IKS01A2/tree/master/examples
Just to have an idea how they are done.
Unfortunately today I do not have band anymore to give a look on your PR. I will do it in the next days.
Thanks in advance and best regards,
Carlo

**Comment by deviousasti** [comment]
I'll try to push some examples.
No hurry. I want activity and wakeup detection, along with low-power mode working on the LSM303AGR, and so I'm building up the API to do that. 
The LSM6 library looks nice.

**Comment by fpistm** [comment]
Hi,
any update on this ?

**Comment by cparata** [comment]
Hi Frederic,
I'm waiting for an example of usage of the new APIs. I would not integrate them until a working example based on these APIs will be provided.
Best Regards,
Carlo

**Comment by fpistm** [comment]
OK Carlo, that's what I thought.
@deviousasti without any update, this PR will be closed due to missing feedback and inactivity.
Could you please provide an example based on your changes?
Thanks in advance.

**Comment by deviousasti** [comment]
Sorry about the delay. 
I haven't been able to get access to the unit which has the LSM303. 
I'll try to work with someone in my team to do it.

**Comment by fpistm** [comment]
OK thanks @deviousasti

**Comment by deviousasti** [comment]
I have added examples which cover most of the new API.
Please have a look @fpistm @cparata 

Have a pleasant day.

**Comment by cparata** [comment]
Thanks a lot @deviousasti ,
next week I will give a try and I will come back to you with a feedback.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hi @deviousasti ,
I gave a look at your fork and this is my feedback:

1. The examples are packaged as .cpp files instead of .ino files. You should create one folder for each sketch and rename the .cpp file as .ino file.

2. I think that temperature example can be removed because the DataLogTerminal example already displays the temperature values.

3. I also noticed some warnings in certain APIs like "SetInterruptDuration" where the "interrupt" parameter is not used, so it should be removed.

4. Regarding the Self Test example, it seems fine to me.

5. Regarding the WakeUp and the Activity examples why did you used pin 6 as interrupt pin? From the schematics of X-NUCLEO-IKS01A2, the interrupt pin of LSM303AGR should be mapped to A3 pin; besides you can use JP12 to select INT1 or INT2. It is not clear what is the hardware setup in your examples. Also, I tried to test the Inactivity example and it generates an interrupt periodically. Should it be the correct behavior of your example? The WakeUp example instead seems working on my side, even if the WakeUp sensitivity seems a bit low on my side.

Unfortunately, I do not have time to work on this topic in the next weeks because I will busy with other urgent tasks, so I apologize if I cannot answer quickly in the next days.

Best Regards,
Carlo

**Comment by fpistm** [comment]
Hi @deviousasti @cparata 
Any update on this ?
Thanks in advance

**Comment by cparata** [comment]
I close this PR because we do not have any update on it

**Pull request closed without merging**
